name: PHPCS check

on: pull_request

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHPCS check ./src
        uses: chekalsky/phpcs-action@v1
        with:
          enable_warnings: true
