name: PHPCS check

on: pull_request

jobs:
  phpcs:
    name: PHPCS
    run: ./vendor/bin/phpcs ${{ steps.changed-files.outputs.all_changed_files }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          enable_warnings: true
