name: PHPCS check

on:
  pull_request:
    paths:
      - "**.php"

jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          enable_warnings: true
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v13.1
        with:
          files: |
            **.php
